# Generated by Django 4.2.29 on 2026-03-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_interest_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
